#!/bin/bash

echo HEADER init

pushd packages || exit 1

pushd harmony_log || exit 1
echo NOTE harmony_log
dart format --fix lib test guide
popd || exit 1

pushd harmony_auth || exit 1
echo NOTE harmony_auth
dart format --fix lib test guide
popd || exit 1

pushd harmony_fire || exit 1
echo NOTE harmony_fire
dart format --fix lib test guide
popd || exit 1

pushd harmony_login || exit 1
echo NOTE harmony_login
dart format --fix lib test guide
popd || exit 1

pushd harmony_login_ui || exit 1
echo NOTE harmony_login_ui
dart format --fix lib test
popd || exit 1

popd || exit 1
